@baseUrl = http://localhost:5000


###
# @name getAllExcel
GET {{baseUrl}}/excel
Content-Type: application/json

###
# @name getExcelById
GET {{baseUrl}}/excel/1
Content-Type: application/json

###
# @name addExcel
POST {{baseUrl}}/excel
Content-Type: application/json

{
    "link":"https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg"
}

###
# @name deleteUser
DELETE  {{baseUrl}}/excel
Content-Type: application/json

{
    "id":6,
    "username":"New User",
    "password":"123",
    "role":"Customer",
    "isBlocked":false
}

###
# @name blockUser
PUT  {{baseUrl}}/excel
Content-Type: application/json

{
    "id":6,
    "username":"New User",
    "password":"123",
    "role":"Customer",
    "isBlocked":true
}

