@baseUrl = http://localhost:5000


###
# @name getAllExcel
GET {{baseUrl}}/api/excel/files
Content-Type: application/json

###
# @name getExcelById
GET {{baseUrl}}/excel/1
Content-Type: application/json

###
# @name addExcel
POST {{baseUrl}}/api/excel/upload
Content-Type: application/json

{
    "data":"https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg"
}

###
# @name deleteUser
DELETE  {{baseUrl}}/excel
Content-Type: application/json

###
# @name blockUser
PUT  {{baseUrl}}/excel
Content-Type: application/json

